### ISSUE TITLE
The benifits of a StringBuilder are negated by the use of String concatenation

### ISSUE THREAD

**Issue by dvberkel** [maartenkoene/ISMetadataVisualisatieTool#10]
In [lines 18 through 22][lines:18-22] you use the following pattern multiple times.

``` java
result.append("a constant string" + aVariable + "another constant");
```

It is better to change it to

``` java
result.append("a constant string").append(aVariable).append("another constant");
```

The reason for this can be found in the way that Java employs [string-interning](http://en.wikipedia.org/wiki/String_interning)

**Comment by maartenkoene** [comment]
this has been fixed
