### ISSUE TITLE
Use Assert.fail() instead of writing to standard output

### ISSUE THREAD

**Issue by dvberkel** [maartenkoene/ISMetadataVisualisatieTool#3]
In the `DatabaseConnectionTest` lines [55](https://github.com/maartenkoene/ISMetadataVisualisatieTool/blob/master/src/test/java/com/infosupport/bi/DatabaseConnectionTest.java#L55) and [74](https://github.com/maartenkoene/ISMetadataVisualisatieTool/blob/master/src/test/java/com/infosupport/bi/DatabaseConnectionTest.java#L74) you write to standard output because an exception is thrown.

I think that in this case it is better to use [`Assert.fail`](http://junit.sourceforge.net/javadoc/org/junit/Assert.html#fail%28java.lang.String%29)

**Comment by maartenkoene** [comment]
I think i fixed it. But maybe we should look at it to make sure its fixed

**Comment by dvberkel** [comment]
Resolved in commit 3a05945e5ba97f2a57e1ad2b885a3bf348adbc55
