### ISSUE TITLE
DataFlowTest contains test about the DataFlowHandler

### ISSUE THREAD

**Issue by dvberkel** [maartenkoene/ISMetadataVisualisatieTool#5]
I would promote [the test](https://github.com/maartenkoene/ISMetadataVisualisatieTool/blob/master/src/test/java/com/infosupport/bi/DataFlowModelTest.java#L63) about the `DataFlowHandler` to a `DataFlowHandlerTest`. This separates the responsibilities of the test.

**Comment by maartenkoene** [comment]
The test has been moved to the correct class. Separating the responsibilities correctly.
