### ISSUE TITLE
What are you testing?

### ISSUE THREAD

**Issue by dvberkel** [maartenkoene/ISMetadataVisualisatieTool#8]
[Line 72](https://github.com/maartenkoene/ISMetadataVisualisatieTool/blob/master/src/test/java/com/infosupport/bi/DataFlowModelTest.java#L72) of `DataFlowModelTest` does not really test anything.

**Comment by maartenkoene** [comment]
This is to see what the list contains and is used to manually print it to the console

**Comment by dvberkel** [comment]
So it is only used as a manual test?
