### ISSUE TITLE
Bobby Tables

### ISSUE THREAD

**Issue by dvberkel** [maartenkoene/ISMetadataVisualisatieTool#9]
The following XKCD [comic](https://xkcd.com/327/) discusses the problems of [SQL injections](http://en.wikipedia.org/wiki/SQL_injection), one of the biggest problems in security.

You code is open to an SQL injection attack. See for example lines [64](https://github.com/maartenkoene/ISMetadataVisualisatieTool/blob/master/src/main/java/com/infosupport/bi/MSSQLQuery.java#L64) and [108](https://github.com/maartenkoene/ISMetadataVisualisatieTool/blob/master/src/main/java/com/infosupport/bi/MSSQLQuery.java#L108).

See the [`java.sql.Connection#prepareStatement`](http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#prepareStatement%28java.lang.String%29) method. (For an example of its usage see this [article](http://software-security.sans.org/developer-how-to/fix-sql-injection-in-java-using-prepared-callable-statement).)

**Comment by maartenkoene** [comment]
This has been fixed.
